plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
rootProject.name = 'Stocker-Backend'

include 'services:identity'
include 'services:catalog'
include 'services:shopping'
include 'services:pricing'
include 'services:notifications'
include 'services:analytics'
include 'services:inventory'
include 'gateway'
