description = 'catalog: product catalog (PostgreSQL)'

dependencies {
	implementation libs.spring.boot.starter.webmvc
	implementation libs.spring.boot.starter.actuator
	implementation libs.spring.boot.starter.data.jpa
	implementation libs.spring.boot.starter.validation
	implementation libs.spring.boot.starter.kafka
	implementation libs.spring.boot.flyway
	implementation libs.flyway.database.postgresql

	runtimeOnly libs.postgresql
	runtimeOnly libs.micrometer.registry.prometheus

	testImplementation libs.spring.boot.starter.webmvc.test
}
