description = 'analytics: analytics and event sink (optional store)'

dependencies {
	implementation libs.spring.boot.starter.webmvc
	implementation libs.spring.boot.starter.actuator
	implementation libs.spring.boot.starter.kafka

	runtimeOnly libs.micrometer.registry.prometheus

	testImplementation libs.spring.boot.starter.webmvc.test
}
