spring:
  application:
    name: catalog
  lifecycle:
    timeout-per-shutdown-phase: 10s
  datasource:
    url: ${STOCKER_DB_URL}
    username: ${STOCKER_DB_USER}
    password: ${STOCKER_DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: stocker.catalog
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: ${SERVER_PORT:8082}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

app:
  kafka:
    producer:
      topics:
        catalog: stocker.catalog.events.v1
    consumer:
      topics: stocker.catalog.events.v1
